### ISSUE TITLE
Excellent work... !!! 

### ISSUE THREAD

**Issue by mora145** [Descolada/UIAutomation#10]
First of all a big THANK YOU for your libraries and all that you have developed. 
I am just starting with Windows automation and this is perfect, very easy to work with and easy to program. The best I have ever used. 

**One question: Do you plan to make it compatible with Ahk v2?**

**Comment by Descolada** [comment]
Thank you for your kind words :)

At this moment I don't have plans on making it AHK v2 compatible, since I don't personally use AHK v2 and this library has more pressing issues to solve. Though if anyone wants to make changes to make it more compatible, of course I will accept the pull requests. 
AFAIK the [UIA2.ahk library](https://github.com/neptercn/UIAutomation/blob/master/UIA2.ahk) should be for AHK v2, perhaps that is suitable?
