### ISSUE TITLE
Firefox Support? How to Limit Search Scope?

### ISSUE THREAD

**Issue by megamorphg** [Descolada/UIAutomation#25]
Would you consider adding Firefox browser functions? I noticed you had an edge function to be able to search just the document area.

I'm trying to do search the "document" area for something but when I do it takes a very long time because I have hundreds of tabs open in the Sidebar--which is considered a "document" area too.

Normally the search through tabs should be quick--it works quickly when I have a browser window open with few tabs.
But I use "Tree Style Tabs" which is an addon that helps manage all these tabs in a side-bar (similar to Edge's vertical tabs feature).

Unfortunately, these are both in the "document" group in the tree... But, the Sidebar document property  is null:

Sidebar document area:
![image](https://user-images.githubusercontent.com/1782353/187355259-d7ce266e-77ee-4609-b0ec-82fd8fd05b87.png)

Actual document area:
![image](https://user-images.githubusercontent.com/1782353/187355217-17da9390-fc2e-4ee6-9a53-6ee0562c5cc4.png)

So if I can do a search to return descendents only where the document is not null, then the search should be much faster. If you see any other way to explicitly define the actual “document” area that would be great, too.

Can you provide examples of limiting the find scope to specific parts of the tree based on various criteria (so that it looks for descendents with the matching scope and doesn’t waste time on other nodes that it should ignore)?

**Comment by Descolada** [comment]
Hello,
Currently I have no plans of supporting Firefox, but I have plans of rewriting the UIA_Browser class to be able to add support for other browsers with less work (to create new classes that extend UIA_Browser, like UIA_Edge and UIA_Firefox). 

I have tested Firefox a little bit and had a few thoughts on how to get the browser element: 

1) Easiest way would be to use a bottom-up approach with ElementFromPoint and then normalize to the document element. This is implemented in UIA_Interface as GetChromiumContentElement(WinTitle, False): try `documentEl := cUIA.GetChromiumContentElement("ahk_id " cUIA.BrowserId, False)`. The drawback is that the browser must be at least partially visible for this to work. 

2) The tab names match the document names, so you could first get the selected tab name, and then try to find the document element. If you inspect Firefox with the UIATreeinspector tool, then you can see that the document elements for all tabs seem to be in a regular order: children of the window element are Custom elements with no name and AutomationId of "panel-n-m", for which the first children is a Pane element and then the Document element. So what I would do is first get the selected tab name; then try to FindAll Custom elements (Treescope_Children:=2), and for each of the found elements get the first childs first child (Document element) and check whether the name matches. Speed optimizations might be possible by determining the number of the selected tab, so you could perhaps filter for "AutomationId=panel-1-n".

**Comment by Descolada** [comment]
Okay, UIA_Browser is now rewritten to be more easily extendable to other browsers. I also added some custom methods to support Firefox (inside UIA_Mozilla class), but I still don't plan to fully support it. I don't use Firefox myself, and it was the hardest and most annoying to automate: Javascript cannot be executed through the URL bar; tabs can't be closed with UIA because the close button isn't an UIA element etc... Though it does have the bonus of being able to access non-active tabs' content, other browsers let you access only the active tab.

**Comment by Descolada** [comment]
I am so sorry, I thought I had tested this but obviously not thoroughly enough. It should be fixed now.

Also `cUIA.WaitPageLoad("New Tab", 3000)` will probably not work, because the title of the browser (for me) is "Mozilla Firefox" not "New Tab", so this will just wait 3 seconds. Also, sometimes WinWaitActive will say the browser is active, but actually the content (buttons, URL bar) hasn't loaded yet, so it's best to add a small sleep as well.

```
browserExe := "firefox.exe"
Run, %browserExe%
WinWaitActive, ahk_exe %browserExe% 
Sleep, 1000
cUIA := new UIA_Browser("ahk_exe " browserExe)
cUIA.WaitPageLoad("Mozilla Firefox", 3000)
cUIA.Navigate("google.com")
cUIA.WaitPageLoad()
MsgBox
```

**Comment by Descolada** [comment]
@megamorphg, WaitPageLoad doesn't require any parameters: if nothing is provided then in addition to waiting for the page to load (stop button to change back to reload button), the method will also wait for the title to change to the correct one.

**Comment by Descolada** [comment]
I think this might be related to what I mentioned earlier: sometimes WinWaitActive will say the browser is active, but actually the content (buttons, URL bar) hasn't loaded yet, so it's best to add a small sleep after WinWaitActive. Perhaps `Sleep 1000` isn't enough? You could try `Sleep 2000` for example. This issue is in my "will eventually try to fix" pile, I haven't figured out a good way to achieve it yet.
