### ISSUE TITLE
high cpu load / memory leak

### ISSUE THREAD

**Issue by megabugman** [Descolada/UIAutomation#30]
UIAViewer causes high CPU load / memory leak, see video:
![memory leaks](https://user-images.githubusercontent.com/17204819/209451406-624687e6-e1ff-4558-b110-28a5794232cf.gif)

Download URL:
https://www.openshot.org/download/

**Comment by Descolada** [comment]
This is not a UIAViewer bug, but instead the problem is somewhere between Microsofts UIAutomation interface and OpenShots implementation for accessibility. Accessibility Insight causes high CPU load and memory leak as well. In addition the same bug is reproduced with AccViewer, which means MSAA implementation is broken too. I haven't noticed other Qt based applications producing such behavior, which makes me think that OpenShot is the problem here. You could report it to OpenShot along with a video of Accessibility Insights causing this problem, perhaps they'll look into it.
