### ISSUE TITLE
Tree is missing a group

### ISSUE THREAD

**Issue by anarkh35** [Descolada/UIAutomation#40]
page: 
http://111.40.190.18:9797/
[![ikBnPN.jpeg](https://i.328888.xyz/2023/03/29/ikBnPN.jpeg)](https://imgloc.com/i/ikBnPN)

**Comment by Descolada** [comment]
Hello,
I am unable to test it out because the website doesn't load for me (times out, takes too long to respond). It is unlikely that there is a bug with UIAInterface.ahk library though, because it doesn't have control over the tree structure. UIA tree is usually based on the Acc tree, and I've noticed some elements get discarded in the conversion because they aren't actually necessary for the tree structure (eg the group might be exactly the same size as the image and only contains the image element, so it isn't useful at all). Also, for example, the tree for Notepad differs significantly between Acc and UIA. 

I am unable to determine whether this difference in trees is actually significant. It looks like the Image element has Invoke pattern available, so it seems like it should be clickable. You are also able to determine the position of the element without problems. Is the missing group causing issues?

**Comment by anarkh35** [comment]
In most cases, the tree found using UIAViewer is reliable.
Due to the lack of attributes on a few pages, only FindByPath can be used. The path found on this page using UIAViewer is incorrect. You must add a "P" before the path to obtain the parent element, which is the correct path.
