### ISSUE TITLE
UIA_interface sets screenreader flag indefinitely

### ISSUE THREAD

**Issue by lcaturelli** [Descolada/UIAutomation#41]
First of all, my sincere thanks for the effort in carrying out this excellent work and selflessly offering it to the entire community.

After executing (without problems) a script with a call to the UIA_Interface() function, the powershell.exe program disables PSReadLine (a very useful module, which is enabled by default) and displays on startup: "Warning: PowerShell detected that it is possible to you're using a screen reader...".

I have been able to verify the cause: [in the first lines](https://github.com/Descolada/UIAutomation/blob/main/Lib/UIA_Interface.ahk#:~:text=enable%20screenreader%20flag%20if%20disabled) of the UIA_Interface() function, the screenreader flag is set (logical and completely understandable) but this flag is not returned to its initial state at any time...

If the session or the computer is restarted, the flag is deactivated again (default option) and powershell works correctly.

The solution I found is to run [this function](https://github.com/PowerShell/PowerShell/issues/11751#issuecomment-600120959) to disable the flag. As @[SeeminglyScience](https://github.com/SeeminglyScience) mentions in his posts: 

>The flag for if a screen reader is active is persistent. So if an application at some point set the flag and then crashed before disabling it (or was written poorly), that flag will stay. This script will turn the flag off. This won't help if you still have a program that is actively setting the flag, but will help in the scenario I described.

I propose to implement a method to deactivate the flag, which we can call at the end of the script. Unfortunately I don't have the necessary knowledge to do it but I think it shouldn't be complicated...

Just in case, the test script I ran is the following:
```
#include UIA_Interface.ahk

UIA := UIA_Interface() ; Initialize UIA interface
cEl := UIA.ElementFromHandle("A") ; Get the element for the current window
if (cEl.FindFirstByName("Ventana modal").Exists){
	Send {Enter}
}
cEl.WaitElementExist("Name=Ventana de notas AND ControlType=Group").FindFirstByName("Más acciones").Click()
cEl.WaitElementExist("Name=Abrir en nueva ventana AND ControlType=Hyperlink").Click()
ExitApp
```

From now, thank you for you help!!

**Comment by Descolada** [comment]
Hello,
Thanks for the input! I wondered whether leaving that flag permanently set would lead to any problems... 
The problem is/was reading the initial screenreader flag and restoring it properly. For example, say that the flag is initially set to 0. Now we run an UIA_Interface script which sets it to 1 and restores to 0 on exit. However, then we run another UIA script that sees it's set to 1 and saves the state. If the first script closes before the second, then the screenreader flag is set to 0, yet an UIA script is still running that might need it at 1. 
Setting the screenreader flag should send a system-wide WM_SETTINGCHANGE message, but in my tests that doesn't seem to be properly happening with SystemParametersInfo fWinIni=2, and fWinIni=3 causes all UIA_Interface scripts to lag at start and exit (like about a 500ms delay for sending the WM_SETTINGCHANGE!). 

So I've decided to push the following change: UIA_Interface() can be called with a activateScreenReader flag set to 0 to avoid setting it altogether. If it's 1, then the global screenreader flag is set to 1 on start, and back to the original state when the script exits. Additionally `UIA_GetScreenReader()` and `UIA_SetScreenReader(state, fWinIni:=2)` functions have been implemented to easily get/set the screenreader flag state.

I hope this fixes the issue.

**Comment by lcaturelli** [comment]
Greetings dear,
Your explanation and solution is very clear.
I confirm that the problem was solved, I just wanted to comment that it throws a Warning on line 4391 (eventually 4393): "The variable screenreader (a local variable) has not been assigned a value" ([#Warn](https://www.autohotkey.com/docs/v1/lib/_Warn.htm))
The above, apparently, does not prevent the execution from ending without problems and it sets back the flag to the original state correctly when the script exits.
Thanks a lot.

**Comment by Descolada** [comment]
No problem. It seems that I forgot to test with #Warn, but it doesn't interfere with script execution and I pushed a fix for it now.
